INSERT INTO public.street (name) VALUES ('Гордіюк')
INSERT INTO public.street (name) VALUES ('Горіхова')
INSERT INTO public.street (name) VALUES ('Горішня')
INSERT INTO public.street (name) VALUES ('Городецька')
INSERT INTO public.street (name) VALUES ('Госпітальна')
INSERT INTO public.street (name) VALUES ('Гостинна')
INSERT INTO public.street (name) VALUES ('Грабова')
INSERT INTO public.street (name) VALUES ('Грабовського')
INSERT INTO public.street (name) VALUES ('Градний узвіз')
INSERT INTO public.street (name) VALUES ('Гребінки')
INSERT INTO public.street (name) VALUES ('Грекова')
INSERT INTO public.street (name) VALUES ('Гречана')
INSERT INTO public.street (name) VALUES ('Григорія Андрузького')
INSERT INTO public.street (name) VALUES ('Григорія Гуляницького')
INSERT INTO public.street (name) VALUES ('Гризодубової')
INSERT INTO public.street (name) VALUES ('Грінченка, пров.')
INSERT INTO public.street (name) VALUES ('Громової')
INSERT INTO public.street (name) VALUES ('Грушевського, майдан')

INSERT INTO public.region (name) VALUES ('Черкаська область'), ('Чернігівська область'), ('Чернівецька область'), ('Дніпропетровська область'), ('Донецька область'), ('Івано-Франківська область'), ('Харківська область'), ('Херсонська область'), ('Хмельницька область'), ('Кіровоградська область'), ('Київська область'), ('Луганська область'), ('Львівська область'), ('Миколаївська область'), ('Одеська область'), ('Полтавська область'), ('Рівненська область'), ('Сумська область'), ('Тернопільська область'), ('Вінницька область'), ('Волинська область'), ('Закарпатська область'), ('Запорізька область'), ('Житомирська область'), ('Київ (місто)'), ('Автономна Республіка Крим (тимчасово окупована Росією)'), ('Севастополь (місто зі спеціальним статусом)');
INSERT INTO public.cities (name) VALUES ('Київ')
INSERT INTO public.cities (name) VALUES        ('Харків')
INSERT INTO public.cities (name) VALUES      ('Одеса')
INSERT INTO public.cities (name) VALUES       ('Дніпро')
INSERT INTO public.cities (name) VALUES      ('Львів')
INSERT INTO public.cities (name) VALUES      ('Запоріжжя')
INSERT INTO public.cities (name) VALUES      ('Кривий Ріг')
INSERT INTO public.cities (name) VALUES      ('Миколаїв')
INSERT INTO public.cities (name) VALUES      ('Вінниця')
INSERT INTO public.cities (name) VALUES     ('Херсон')
INSERT INTO public.cities (name) VALUES       ('Полтава')
INSERT INTO public.cities (name) VALUES        ('Чернігів')
INSERT INTO public.cities (name) VALUES        ('Черкаси')
INSERT INTO public.cities (name) VALUES        ('Житомир')
INSERT INTO public.cities (name) VALUES        ('Суми')
INSERT INTO public.cities (name) VALUES        ('Рівне')
INSERT INTO public.cities (name) VALUES        ('Тернопіль')
INSERT INTO public.cities (name) VALUES       ('Івано-Франківськ')
INSERT INTO public.cities (name) VALUES       ('Луцьк')
INSERT INTO public.cities (name) VALUES       ('Ужгород')

INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES (3, 14, 7, 223, 417, 54023, 'Б'),(15, 25, 12, 482, 176, 61112, 'В'),(18, 11, 16, 369, 35, 76131, 'А'),(8, 5, 2, 207, 211, 82341, 'Б'),(5, 19, 5, 128, 184, 68850, 'А'),(14, 3, 15, 356, 95, 50412, 'В'),(9, 7, 10, 40, 318, 83502, 'А'),(12, 8, 4, 352, 157, 56217, 'Б'),(6, 9, 8, 327, 359, 44777, 'Б'),(17, 6, 9, 222, 244, 69345, 'А')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES (10, 2, 3, 89, 99, 48882, 'А')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (2, 23, 14, 176, 482, 60231, 'В')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (11, 13, 11, 381, 432, 74536, 'А')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (19, 17, 18, 449, 254, 57914, 'В')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (7, 10, 1, 345, 178, 46444, 'А')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (4, 22, 6, 212, 55, 71290, 'Б')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (16, 1, 13, 117, 398, 57890, 'А')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (13, 16, 17, 275, 75, 82111, 'Б')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (20, 15, 10, 193, 123, 50245, 'В')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (1, 18, 8, 49, 295, 75325, 'Б')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (3, 14, 7, 223, 417, 54023, 'А')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (15, 25, 12, 482, 176, 61112, 'Б')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (18, 11, 16, 369, 35, 76131, 'В')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (8, 5, 2, 207, 211, 82341, 'А')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (5, 19, 5, 128, 184, 68850, 'Б')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (14, 3, 15, 356, 95, 50412, 'В')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (9, 7, 10, 40, 318, 83502, 'Б')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (12, 8, 4, 352, 157, 56217, 'А')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES      (6, 9, 8, 327, 359, 44777, 'Б')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (17, 6, 9, 222, 244, 69345, 'В')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (10, 2, 3, 89, 99, 48882, 'Б')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (2, 23, 14, 176, 482, 60231, 'А')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES      (11, 13, 11, 381, 432, 74536, 'В')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES      (19, 17, 18, 449, 254, 57914, 'А')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (7, 10, 1, 345, 178, 46444, 'Б')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (4, 22, 6, 212, 55, 71290, 'В')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (16, 1, 13, 117, 398, 57890, 'Б')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (13, 16, 17, 275, 75, 82111, 'А')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES       (20, 15, 10, 193, 123, 50245, 'Б')
INSERT INTO public.addresses (city_id, region_id, street_id, apartment, build, postal, sub_build) VALUES      (1, 18, 8, 49, 295, 75325, 'А');

INSERT INTO public.clients (client_address_id, created_at, abb_name, client_status, client_type, full_name, ipn, telephone_number) VALUES (3, '2023-07-10 14:23:45', 'FOP Bohush', 'ACTIVE', 'WHOLESALE', 'Serhii Bohush O', '4562455514', '0958651489');
INSERT INTO public.clients (client_address_id, created_at, abb_name, client_status, client_type, full_name, ipn, telephone_number) VALUES (17, '2023-05-22 09:15:30', 'ABC Trading', 'NO_CONTRACT', 'RETAIL', 'Anna Kovalenko', '1234567890','0671234567');
INSERT INTO public.clients (client_address_id, created_at, abb_name, client_status, client_type, full_name, ipn, telephone_number) VALUES (8, '2023-03-14 18:45:12', 'XYZ Corp', 'EXPIRED', 'VIP', 'Viktor Petrovich Ivanov', '9876543210', '0987654321');
INSERT INTO public.clients (client_address_id, created_at, abb_name, client_status, client_type, full_name, ipn, telephone_number) VALUES (11, '2023-08-05 12:34:56', 'Sunrise Retail', 'ACTIVE', 'RETAIL', 'Olga Mykhailivna Hrytsyuk', '5432109876','0639876543');
INSERT INTO public.clients (client_address_id, created_at, abb_name, client_status, client_type, full_name, ipn, telephone_number) VALUES (25, '2023-09-18 20:10:30', 'Elite Partners', 'IN_SIGN', 'VIP', 'Andriy Fedorovych Voronov', '3210987654', '0976543210');
INSERT INTO public.clients (client_address_id, created_at, abb_name, client_status, client_type, full_name, ipn, telephone_number) VALUES (6, '2023-02-28 08:55:20', 'FOP XYZ', 'ACTIVE', 'RETAIL', 'Yulia Ivanivna Petrova', '8765432109', '0665432109');
INSERT INTO public.clients (client_address_id, created_at, abb_name, client_status, client_type, full_name, ipn, telephone_number) VALUES (14, '2023-04-15 16:30:45', 'Sunset Traders', 'NO_CONTRACT', 'WHOLESALE', 'Petrov Retail Group', '5432109876', '0987654321')
INSERT INTO public.clients (client_address_id, created_at, abb_name, client_status, client_type, full_name, ipn, telephone_number) VALUES (9, '2023-06-20 11:22:33', 'Golden Deals', 'ACTIVE', 'VIP', 'Natalia Kuznetsova', '9876543210', '0567890123')
INSERT INTO public.clients (client_address_id, created_at, abb_name, client_status, client_type, full_name, ipn, telephone_number) VALUES (20, '2023-01-12 04:40:15', 'Silver Enterprises', 'EXPIRED', 'RETAIL', 'Dmytro Fedorov', '6543210987', '0991234567')
INSERT INTO public.clients (client_address_id, created_at, abb_name, client_status, client_type, full_name, ipn, telephone_number) VALUES (12, '2023-10-03 22:11:55', 'Moonlight Wholesalers', 'ACTIVE', 'WHOLESALE', 'Mykola Tkachenko', '9876543210', '0678901234')
INSERT INTO public.clients (client_address_id, created_at, abb_name, client_status, client_type, full_name, ipn, telephone_number) VALUES (19, '2023-11-08 19:14:27', 'Crystal Retail', 'IN_SIGN', 'RETAIL', 'Yevhenia Kovalchuk', '1234567890', '0954321098')